"""
netscan/report_generator.py
------------------------------
Step 3 of the pipeline. Takes the structured scan results from
vuln_scanner.py and produces a formatted PDF report with a summary page
and per-host findings + remediation advice.

Requires: pip install reportlab
"""

import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)

from .remediation import get_remediation

SEVERITY_COLORS = {
    "critical": colors.HexColor("#7a0d0d"),
    "high": colors.HexColor("#c0392b"),
    "medium": colors.HexColor("#d68910"),
    "low": colors.HexColor("#2e86c1"),
    "info": colors.HexColor("#616a6b"),
}

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


# =================================================================================================================
def _count_by_severity(results):
    counts = {s: 0 for s in SEVERITY_ORDER}
    for host in results:
        for finding in host.get("findings", []):
            sev = finding.get("severity", "info")
            counts[sev] = counts.get(sev, 0) + 1
    return counts
# =================================================================================================================


# =================================================================================================================
def generate_report(results, network_label, output_path="network_report.pdf"):
    """
    results: list of per-host dicts as produced by vuln_scanner.scan_hosts()
    network_label: string describing what was scanned (e.g. "192.168.1.0/24")
    output_path: path to write the PDF to
    """
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=1.8*cm, rightMargin=1.8*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], fontSize=22)
    h2 = styles["Heading2"]
    h3 = styles["Heading3"]
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=body, fontSize=8, textColor=colors.grey)

    story = []

    # ---- Title page ----
    story.append(Paragraph("Network Security Scan Report", title_style))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph(f"Target: {network_label}", body))
    story.append(Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body))
    story.append(Paragraph(f"Hosts scanned: {len(results)}", body))
    story.append(Spacer(1, 0.8*cm))

    # ---- Summary counts ----
    counts = _count_by_severity(results)
    story.append(Paragraph("Findings Summary", h2))
    summary_data = [["Severity", "Count"]]
    for sev in SEVERITY_ORDER:
        summary_data.append([sev.upper(), str(counts[sev])])
    summary_table = Table(summary_data, colWidths=[6*cm, 4*cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.4*cm))
    story.append(Paragraph(
        "Note: This report is generated by automated tooling (nmap service/version "
        "detection and vulnerability scripts). Findings should be reviewed and "
        "validated before acting on them, and this scan should only ever be run "
        "against networks/hosts you own or have explicit permission to test.",
        small
    ))
    story.append(PageBreak())

    # ---- Per-host sections ----
    for host in results:
        ip = host.get("ip", "unknown")
        story.append(Paragraph(f"Host: {ip}", h2))

        if host.get("error"):
            story.append(Paragraph(f"Error scanning this host: {host['error']}", body))
            story.append(Spacer(1, 0.5*cm))
            continue

        findings = host.get("findings", [])
        if not findings:
            story.append(Paragraph("No open ports/services detected.", body))
            story.append(Spacer(1, 0.5*cm))
            continue

        # Sort findings by severity so the worst issues appear first
        findings_sorted = sorted(
            findings,
            key=lambda f: SEVERITY_ORDER.index(f.get("severity", "info"))
        )

        for finding in findings_sorted:
            sev = finding.get("severity", "info")
            sev_color = SEVERITY_COLORS.get(sev, colors.grey)
            port = finding.get("port")
            service = finding.get("service", "unknown")
            product = finding.get("product", "")
            version = finding.get("version", "")

            header_style = ParagraphStyle(
                "FindingHeader", parent=h3, textColor=sev_color
            )
            story.append(Paragraph(
                f"[{sev.upper()}] Port {port}/{finding.get('protocol','tcp')} — {service} {product} {version}".strip(),
                header_style
            ))

            if finding.get("script"):
                story.append(Paragraph(f"<b>Detection script:</b> {finding['script']}", body))

            story.append(Paragraph(f"<b>Raw finding:</b> {finding.get('output', '')}", body))

            risk_text, fix_text = get_remediation(finding)
            story.append(Paragraph(f"<b>Why it matters:</b> {risk_text}", body))
            story.append(Paragraph(f"<b>Recommended fix:</b> {fix_text}", body))
            story.append(Spacer(1, 0.35*cm))

        story.append(Spacer(1, 0.4*cm))

    doc.build(story)
    return output_path
# =================================================================================================================


if __name__ == "__main__":
    import sys
    import json

    if len(sys.argv) < 2:
        print("Usage: python -m netscan.report_generator <scan_results.json> [output.pdf]")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        results = json.load(f)

    out_path = sys.argv[2] if len(sys.argv) > 2 else "network_report.pdf"
    generate_report(results, network_label="(from JSON file)", output_path=out_path)
    print(f"Report written to {out_path}")
